### ISSUE TITLE
Dot stroke

### ISSUE THREAD

**Issue by RayPS** [indus/Zodiac#1]
Thank you i think this is better than particleground.
Can i remove the dot stroke?

**Comment by RayPS** [comment]
I fixed this by setting the same color on linkColor and dotColor,
but i found another issue.

The canvas will be empty if you set dotRadius: [3, 3]

**Comment by indus** [comment]
I think 94ac0536bb1a13c38dd103d5b923945a4884ccc5 should fix the issue. I will have a closer look at the weekend if not...

**Comment by indus** [comment]
I think I fixed it with 037600acf91d61039ffab6c12df30f5c3935dc50
Now, you can also use number for `dotRadius` without getting urgly lines inside the dots.
Is that what you meen with "dot stroke"
