### ISSUE TITLE
Any performance improvements that could be done?

### ISSUE THREAD

**Issue by agauniyal** [indus/Zodiac#4]
particles.js takes much less cpu (around 40-50%) than zodiac which is taking almost double(70-80%) cpu processing. could we expect any performance improvements in future?

Thank you :smile:

**Comment by agauniyal** [comment]
| Name | Time | % |
| --- | --- | --- |
| (Program) | 470.0ms | 63.52% |
| `arc` | 84.9ms | 11.47% |
| `update` | 160.7ms | 22.57% |
| `moveTo`/ `stroke`/ `clearRect` | ~15ms | ~2% |

**Comment by agauniyal** [comment]
also performance on mozilla is worse than on chrome. running zodiac on an old machine with up to date firefox makes even scrolling a painful experience.

**Comment by agauniyal** [comment]
These might help for reference - 
- http://www.html5rocks.com/en/tutorials/canvas/performance/
- https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas

**Comment by indus** [comment]
Why don't you just use particle.js when it is more performant? Even I now consider using it for JS.ORG  if it is that much better.

**Comment by agauniyal** [comment]
I don't want to include another library(jquery) for including one library. This seems much better in terms of simplicity and ease of use. Sadly I'm not familiar with canvas and stuff, otherwise I would have sent an PR instead of opening an issue.

Don't get me wrong, I'm already using this library and its working as intended. I'm just asking if you plan to make any improvements so that other users could be benefited :smile:.

**Comment by indus** [comment]
I really don't know why performance is worse then in another library and I think I have the time right now to investigate on it (maybe some hard to debug deoptimication of code)

A not wanted jQuery dependecy was the main reason for me to write zodiac. But it really should be trivial to strip jQuery from particle.js . There is only little use for it in a canvas library: measure the canvas, bind events to it, initialize the code. If you know how to do these things without jQuery it should be a simple task to rewrite.

**Comment by agauniyal** [comment]
Thankyou :smile: I'll look into it.
